apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-git-tag
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Task to generate a build tag
  workspaces:
    - name: source
  results:
    - name: build-tag
      description: ID of the current build
  steps:
    - name: get-buildtag
      image: quay.io/michard/developer_image:tekton-push
      script: |
        #!/bin/sh
        pwd
        ls
        cd $(workspaces.source.path)
        echo start
        git config --global --add safe.directory /workspace/source
        pwd
        ls
        git fetch --tags
        echo 1
        git describe --tags
        echo 15
        git rev-list --tags --max-count=1
        echo 16
        buildtag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo 2
        echo "Current Build Tag: ${buildtag}"
        echo 3
        echo ${buildtag} | tr -d "\n" | tee $(results.build-tag.path)
        echo 4